// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://ovptpcaxxbynoaehkzta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92cHRwY2F4eGJ5bm9hZWhrenRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODA2ODgsImV4cCI6MjA3MjY1NjY4OH0.D9DSRnOg3MMCmTUpmq8VUe3kGIyFUFWxsHfznKk0qgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);